name: 'fraud_analytics'
version: '1.0.0'
config-version: 2

profile: 'fraud_analytics_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fraud_analytics:
    staging:
      +materialized: view
    core:
      +materialized: table
    marts:
      +materialized: table