fraud_analytics:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: jcdeah-006 # GCP Project ID
      dataset: zidan_finpro_analytics # BigQuery Dataset
      threads: 4
      keyfile: /opt/airflow/keys/gcp_key.json
      timeout_seconds: 300
      location: asia-southeast2 