fraud_analytics:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: finpro-purwadhika
      dataset: zidan_finpro
      location: us-west1
      keyfile: /opt/airflow/keys/gcp_key.json
      threads: 1
      timeout_seconds: 3600
