name: fraud_analytics
version: 1.0.0
config-version: 2

profile: fraud_analytics_profile

model-paths: ["models"]
target-path: target

models:
  fraud_analytics:
    staging:
      +materialized: table
    core:
      +materialized: table
    marts:
      +materialized: table